name: Test

on:
  workflow_call:

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Run Unit Tests with Coverage
        run: ./gradlew koverMergedReport --stacktrace

      - name: Report Coverage
        uses: codecov/codecov-action@v3
        with:
          files: build/reports/kover/merged/xml/report.xml
          flags: unit